### ISSUE TITLE
NoMethodError/nil-ref when using persisted queries

### ISSUE THREAD

**Issue by ktalley** [jetruby/graphql-rails_logger#12]
We recently switched to using [persisted queries](https://www.apollographql.com/docs/react/api/link/persisted-queries/#how-it-works) using [this Rails gem](https://github.com/DmitryTsepelev/graphql-ruby-persisted_queries).

We now get a nil-ref error on this line:
https://github.com/jetruby/graphql-rails_logger/blob/master/lib/graphql/rails_logger/subscriber.rb#L42

`Could not log "start_processing.action_controller" event. NoMethodError: undefined method 'lines' for nil:NilClass`

This is most likely caused by the fact the persisted query doesn't send along a `query` param, just a hash that the backend maps to the query. I think adding a check to this method to make sure `data['query'].present?` before trying to format should fix it.

Here's an example request:
`https://localhost:3000/api/graphql?operationName=appBootstrap&variables={"userId":"abcd1234"}&extensions={"persistedQuery":{"version":1,"sha256Hash":"832db74c644f9a1e8123be4a6f7e19ade39fc9c590c4a75c7a7ffb2f2ab55948"}}`

Thanks in advance!

**Comment by fuelen** [comment]
Hey @ktalley 
I do not work with ruby and rails for a long time, but I'd happy to apply the fix if you prepare a PR :)

**Comment by fuelen** [comment]
pushed to rubygems :tada:
