### ISSUE TITLE
Text invisible on white-background terminals

### ISSUE THREAD

**Issue by mhuggins** [jetruby/graphql-rails_logger#5]
I use black-on-white terminals, and the text is not legible.  Would love to be able to use this gem!

![screen shot 2018-12-17 at 11 34 55 pm](https://user-images.githubusercontent.com/169093/50134179-7847f180-0254-11e9-8cfe-30f1ae5004ed.png)

**Comment by fuelen** [comment]
We use https://github.com/jneen/rouge for highlighting, you can play with formatter here https://github.com/jetruby/graphql-rails_logger/blob/master/lib/graphql/rails_logger/subscriber.rb#L33.
PRs with improvements are welcome :)

**Comment by sshaw** [comment]
Had the same problem. What do you think about `config.theme` accepting a `String` for a theme that is subsequently looked up? 

The idea being devs can set this via an env var as they see fit without affecting what others do

**Comment by fuelen** [comment]
@sshaw there is not need in handling this case in a library. You can resolve this by yourself using something like this:
```
config.theme = (ENV["THEME_NAME"] ? Object.const_get(ENV["THEME_NAME"]) : Rouge::Themes::ThankfulEyes).new
```

**Comment by sshaw** [comment]
🆒 thanks @fuelen!

**Comment by sshaw** [comment]
But with this approach, one cannot call dark/light etc.. on the theme

**Comment by fuelen** [comment]
@sshaw what do you mean?
