### ISSUE TITLE
Is it possible to prevent syntax highlighting?

### ISSUE THREAD

**Issue by leshik** [jetruby/graphql-rails_logger#7]
Hi,
I'm using Concourse CI that has a [bug](https://github.com/concourse/concourse/issues/2390) in its webUI that causes text blinking when using some ANSI colors. Is it possible to completely turn off ANSI highlighting somehow?

**Comment by fuelen** [comment]
Hello.
Yes, it is possible. You can add support for a new flag and apply it [here](https://github.com/jetruby/graphql-rails_logger/blob/b7bf817c0cc96c63ac06d9a44c2cd841e38b682f/lib/graphql/rails_logger/subscriber.rb#L44).
Also, you can disable this gem for test environment (if the problem only in it).
