### ISSUE TITLE
NameError: uninitialized constant GraphQL::RailsLogger::Subscriber::PP

### ISSUE THREAD

**Issue by imcvampire** [jetruby/graphql-rails_logger#9]
Just adding your gem to a new GraphQL-ruby project and I face a problem 

```
Could not log "start_processing.action_controller" event. NameError: uninitialized constant GraphQL::RailsLogger::Subscriber::PP
```

Can you help me to check and resolve that problem?

Thank you!

**Comment by pedrogimenez** [comment]
Add `require "pp"` to your `config/application.rb`.

**Comment by imcvampire** [comment]
Thank @pedrogimenez. It works!
